//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Test_List.Views.Student.ORMDataModel1
{

    public partial class students : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string femail;
        [Indexed(Name = @"UQ__students__AB6E616465CCB695", Unique = true)]
        [Size(150)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fphone;
        [Size(20)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>(nameof(phone), ref fphone, value); }
        }
        string faddress;
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        DateTime fcreated_at;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>(nameof(created_at), ref fcreated_at, value); }
        }
    }

}
